#theme: jekyll-theme-minimal
remote_theme: jekyll/minima
title: <div align="center"><img src="/images/jks.jpg" width="200"/></div>
description: Out here trying my best.<br /><br /><a href="https://github.com/jksmith9" target="_blank"><img src="images/github.png" width="23"/></a>&nbsp;&nbsp;<a href="https://www.linkedin.com/in/jksncsu/" target="_blank">  <img src="images/linkedin.png" width="23"/>
google_analytics: G-SN4T9SRSPB

plugins:
  - jekyll-theme-minimal
